#  Water vapor column mass flux figures, comparing NARR, MERRA2, and ERA5. 

import os
import re
import argparse
import numpy as np
from netCDF4 import Dataset
import matplotlib.pyplot as plt 
from matplotlib import ticker 
import cartopy.crs as ccrs
import cartopy.feature as cfeature 
from .libpod import get_metricpath
from ..parameters import boundaries, regions
import warnings


warnings.filterwarnings("ignore")

#  Location of the data. 

DATAROOT = os.getenv( "DATAROOT" )
print( f'DATAROOT = {DATAROOT}' )

#  Default plotting parameters. 

axeslinewidth = 0.5 
plt.rcParams.update( {
  'font.family': "Times New Roman", 
  'font.size': 8,  
  'font.weight': "normal", 
  'text.usetex': True, 
  'xtick.major.width': axeslinewidth, 
  'xtick.minor.width': axeslinewidth, 
  'ytick.major.width': axeslinewidth, 
  'ytick.minor.width': axeslinewidth, 
  'axes.linewidth': axeslinewidth } ) 

months = 'Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec'.split()

#  Choose the definition of the column. 

scale = 8.0e3
wvscale = 0.005 * scale


#  Function to define an axes for vector field plotting. 

def def_ax( fig, bounds=[0.05,0.05,0.90,0.90], fontsize=None ): 
    """This is the template for the map, including projection definition read 
    from the Lambert_Conformal variable attributes and generated by def_projdict. 
    The fig is defined by pyplot.figure, and the bounds are sent to the definition 
    of the axes. The axes are returned."""

    ax = fig.add_axes( bounds, projection=ccrs.PlateCarree() )
    ax.set_extent([-135,-60,15,55], ccrs.PlateCarree())
    ax.add_feature(cfeature.OCEAN,facecolor='paleturquoise',alpha=0.4)
    ax.coastlines(lw=0.5)
    gl = ax.gridlines(crs=ccrs.PlateCarree(), draw_labels=False, 
                      x_inline=False, y_inline=False, linewidth=0.33, 
                      color='k', alpha=0.5 )
    gl.right_labels = gl.top_labels = False
    gl.ylocator = ticker.FixedLocator( np.arange(20,60,10) )
    gl.xlocator = ticker.FixedLocator( np.arange(-120,-59,15) )
    if fontsize is not None: 
        gl.xlabel_style = {'size': fontsize }
        gl.ylabel_style = {'size': fontsize }

    return ax


def read_metadata( datapath, metadata:dict={} ): 

    if not os.path.exists( datapath ): 
        print( f'Data file {datapath} does not exist. Exiting' )
        return None

    d = Dataset( datapath, 'r' )
    if "lon" in d.variables.keys(): 
        lons = d.variables['lon'][:]
        lats = d.variables['lat'][:]
    elif "longitude" in d.variables.keys(): 
        lons = d.variables['longitude'][:]
        lats = d.variables['latitude'][:]

    d.close()
    metadata.update( { 'path': datapath, 'lons': lons, 'lats': lats } )

    return metadata


def plot_watervaporflux( analyses:list, layer:str, outputfile:str, nx:int=2, ): 
    """Annual average, diurnal average atmospheric mass flux"""

    nanalyses = len( analyses )
    ny = int( ( nanalyses - 1 ) / nx ) + 1

    fig = plt.figure( figsize=(3*nx,1.8*ny) )

    for ianalysis, analysis in enumerate( analyses ): 

        ix = ianalysis % nx
        iy = ny - int(ianalysis/nx) - 1

        pos = np.array( [0.02+ix,0.01+iy,0.92,0.81] ) / np.array( [nx,ny,nx,ny] )
        ax = def_ax( fig, bounds=pos )

        d = Dataset( analysis['path'], 'r' )
        groupnames = list( d.groups.keys() )
        if layer not in groupnames: 
            print( f'Layer "{layer}" not in file; valid layers are ' + \
                  ", ".join( [f'"{l}"' for l in groupnames] ) )
            return

        g = d.groups[layer]

        uwvf_avg = g.variables['uwvf'][:].mean(axis=0).mean(axis=0)
        vwvf_avg = g.variables['vwvf'][:].mean(axis=0).mean(axis=0)
        lons = analysis['lons']
        lats = analysis['lats']
        nxskip, nyskip = analysis['nxskip'], analysis['nyskip']

        d.close()

        if len( analysis['lons'].shape ) == 2: 
            ax.quiver( lons[::nyskip+1,::nxskip+1], lats[::nyskip+1,::nxskip+1], \
                    uwvf_avg[::nyskip+1,::nxskip+1], vwvf_avg[::nyskip+1,::nxskip+1], \
                    transform=ccrs.PlateCarree(), scale=wvscale, scale_units="xy" )
        else: 
            ax.quiver( lons[::nxskip+1], lats[::nyskip+1], \
                    uwvf_avg[::nyskip+1,::nxskip+1], vwvf_avg[::nyskip+1,::nxskip+1], \
                    transform=ccrs.PlateCarree(), scale=wvscale, scale_units="xy" )

        title = "({:}) {:}".format( chr(ord("a")+ianalysis), analysis['name'] )
        ax.text( -135, 57, title, ha="left" )

        f = 5
        if ianalysis == int( nanalyses/2 ): 
            ax.quiver( [-57.5], [20], [0], [f*wvscale], 
                    transform=ccrs.PlateCarree(), scale=wvscale, scale_units="xy", 
                    clip_on=False )
            ax.text( -58, 28, f'{f*wvscale:.1f} kg/m/s', rotation="vertical", ha="left", clip_on=False )

        if ianalysis == nanalyses-1: 
            regb = boundaries['great-plains']
            ax.plot( regb['lons'], regb['lats'], lw=1.2, color="red" )
            reg = [ reg for reg in regions if reg['name']=="great-plains" ][0]
            x = np.array( [ reg['longituderange'][0], reg['longituderange'][1], reg['longituderange'][1], reg['longituderange'][0], reg['longituderange'][0] ] )
            y = np.array( [ reg['latituderange'][0], reg['latituderange'][0], reg['latituderange'][1], reg['latituderange'][1], reg['latituderange'][0] ] )
            ax.plot( x, y, lw=1.2, color="blue" )

    print( f'Saving to {outputfile}.' )
    fig.savefig( outputfile )

    return


def main(): 

    parser = argparse.ArgumentParser( prog="watervaporflux", 
                 description="Compose a plot of PBL water vapor mass flux" )

    parser.add_argument( "modelroot", type=str, 
            help="The root directory of the model output" )

    default_layer = "column"
    parser.add_argument( "--layer", dest="layer", default="column", 
            help=f'The name of the layer to diagnose; the default is "{default_layer}".' )

    parser.add_argument( "--label", dest="label", default="", 
            help="The nominal label of the model run" )

    default_output = "watervaporflux.pdf"
    parser.add_argument( "--output", "-o", dest="outputfile", default=default_output, 
            help=f'The output figure file. The default is "{default_output}".' )

    parser.add_argument( "--pdb", dest="pdb", default=False, action="store_true", 
            help="Run in the Python line debugger PDB." )

    args = parser.parse_args()


    if args.pdb: 
        import pdb
        pdb.set_trace()

    #  Reanalysis specifics. 

    reanalyses = [ { 'name': 'NARR', 'nxskip': 7, 'nyskip': 7 }, 
            { 'name': 'MERRA2', 'nxskip': 4, 'nyskip': 4 }, 
            { 'name': 'ERA5', 'nxskip': 10, 'nyskip': 8 }
            ]

    for reanalysis in reanalyses: 
        path = get_metricpath( "watervaporflux", reanalysis['name'].lower() )
        read_metadata( path, reanalysis ) 

    if args.label == "": 
        label = os.path.split( args.modelroot )[-1]
    else: 
        label = str( args.label )

    #  Read in model metadata. 

    model = { 'nxskip': 2, 'nyskip': 2, 'name': label }
    datapath = os.path.join( args.modelroot, "watervaporflux", "watervaporflux.nc" )
    model = read_metadata( datapath, model )

    #  Generate figure. 

    plot_watervaporflux( reanalyses + [ model ], args.layer, args.outputfile )
    return


if __name__ == "__main__": 
    main()
    pass

